FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o supershadowvpn-client ./client

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/supershadowvpn-client .
COPY --from=builder /app/config/config.json .

EXPOSE 1080

CMD ["./supershadowvpn-client"]