version: '3.8'

services:
  supershadowvpn:
    build: .
    container_name: supershadowvpn
    restart: unless-stopped
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "51820:51820/udp"
    volumes:
      - ./configs:/root/clients
    devices:
      - /dev/net/tun