FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o supershadowvpn-server ./server

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /app/supershadowvpn-server .
COPY --from=builder /app/config/config.json .

EXPOSE 8080

CMD ["./supershadowvpn-server"]